### ISSUE TITLE
stoa0040.stoa015a.opp-lat1.xml ajout de balises refsDecl, changement de mes balises div suite au test sur Capitains

### ISSUE THREAD

**Issue by CelCpc** [Chartes-TNAH/patrologia_latina-dev#104]
J'ai finalement procédé à l'ajout des balises refsDecl dans le TEI header. 

Suite au test sur Capitains (https://capitains-validator.herokuapp.com/) je me suis rendue compte que les balises <div> précédemment numérotées avaient été mal réalisées. En effet, j'avais opté pour une suite numérique comme suit : 15.1, 15.2, 15.3... ce qui ne semble pas autorisé.
#99 

Après cette correction j'ai pushé mon devoir sur mon repository GitHub sur ma branche revision : https://github.com/CelCpc/patrologia_latina-dev/tree/revision

**Comment by dalliaume** [comment]
Vérification réussie
