### ISSUE TITLE
Capitainisation du fichier stoa0040.stoa013a.opp-lat1.xml 

### ISSUE THREAD

**Issue by CelCpc** [Chartes-TNAH/patrologia_latina-dev#106]
Bonjour, 

J'aimerais que quelqu'un vérifie mon travail et le choix des nouvelles balises div ajoutées en vue de la capitainisation de ce texte. Dois-je intervenir à d'autres niveaux ?

**Comment by dalliaume** [comment]
Bonjour, 
La capitainisation du texte est réussie.

**Comment by CelCpc** [comment]
Bien que la capitainisation soit réussie, j'ai tout de même corrigé d'autres erreurs d'océrisation.
