### ISSUE TITLE
Remplacement des æ en ae

### ISSUE THREAD

**Issue by dalliaume** [Chartes-TNAH/patrologia_latina-dev#108]
Les æ ont été remplacés en ae au sein du fichier, avec l'aide d'une recherche/remplace.

**Comment by CelCpc** [comment]
Sauf erreur de ma part le commit correspondant au remplacement des ae est en fait un espace qui a été supprimé : https://github.com/Chartes-TNAH/patrologia_latina-dev/pull/113/commits/db6750789ff6c2ede3fbbf2490fa79401a50c93e

**Comment by dalliaume** [comment]
En effet, j'ai fais une erreur dans le titre d'un commit. J'ai voulu montrer que les ae avaient été remplacés dans un commit factuel.
