### ISSUE TITLE
Régularisation hyphénisations

### ISSUE THREAD

**Issue by dalliaume** [Chartes-TNAH/patrologia_latina-dev#109]
Les hyphénisations ont été corrigées.

**Comment by CelCpc** [comment]
Après vérification ce sont ici les ae qui ont été corrigées https://github.com/Chartes-TNAH/patrologia_latina-dev/pull/113/commits/478159d409133118d38351fdef4d1960ef6e5540

**Comment by dalliaume** [comment]
En effet, j'ai fais une erreur dans le titre d'un commit. Je confirme que ce sont bien les ae qui ont été corrigées pour l'issue #109.
