### ISSUE TITLE
Organisation du texte en div pour les chapitres

### ISSUE THREAD

**Issue by dalliaume** [Chartes-TNAH/patrologia_latina-dev#110]
Le texte a été organisé au sein de balises div pour les chapitres.

**Comment by CelCpc** [comment]
Ce sont les hyphénisations qui ont été retirées dans lors du commit Organisation du texte en div pour les chapitres : https://github.com/Chartes-TNAH/patrologia_latina-dev/pull/113/commits/45b0befef41aea87a06df8e7271cea7cb243b2ae

**Comment by dalliaume** [comment]
Remarque prises en compte, l'erreur est due à un erreur de titre dans un commit précédent.

**Comment by dalliaume** [comment]
Remarques prises en compte, l'erreur est due à un erreur de titre dans un commit précédent.

**Comment by CelCpc** [comment]
Très bien, j'en prends note et valide la modification de ce texte
