### ISSUE TITLE
Stoa0040.stoa015 -> Finalisation de la correction de l'OCR + footnote

### ISSUE THREAD

**Issue by LucetteV** [Chartes-TNAH/patrologia_latina-dev#128]
Bonjour,
J'ai terminé la correction de l'OCR jusqu'au chapitre 13. Les notes de bas de page sont toutes reprises, et j'ai également tenté d'apporter une correction sur les passages en grec.
En attente de validation par @Lwizzzzzz .

LucetteV

**Comment by Lwizzzzzz** [comment]
Après consultation des dernières modifications effectuées par @LucetteV (se référer à la pull request #76 ), je confirme que la correction de l'OCR a été achevée jusqu'au chapitre 13 (un commentaire indique où s'arrête la partie corrigée).

**Comment by LucetteV** [comment]
Merci @Lwizzzzzz pour ta réactivité.

Bonne fin de week-end,
Lucie
