### ISSUE TITLE
(stoa0040.stoa025a) Correction approfondie de l'OCR

### ISSUE THREAD

**Issue by olivierjacquot** [Chartes-TNAH/patrologia_latina-dev#14]
Compte tenu de la qualité de l'édition source, l'OCR comporte un nombre certain d'erreurs, chronophages à corriger. Tout bonne volonté est bienvenue pour faire une passe complète sur le document.

**Comment by olivierjacquot** [comment]
En effet, l'OCR n'a pas fait de miracles compte tenu de la taille des caractères et de leur mauvaise impression... Ce sera dur de trouver une bonne âme qui se dévouera.

**Comment by EmilieBlotiere** [comment]
le pull request #20 répond à cette issue, que nous pouvons donc fermer.
