### ISSUE TITLE
(0040.015a) Remettre les `<lb />`

### ISSUE THREAD

**Issue by PonteIneptique** [Chartes-TNAH/patrologia_latina-dev#163]

**Comment by CelCpc** [comment]
Bonjour professeur @PonteIneptique,

Je viens de me rendre compte que j'avais mal noté les consignes dans mon cours, je cite "supprimer les balises <lb> et les retours à la ligne, ou au moins supprimer les espaces autours des balises <lb>".

Je suis en train de retravailler le fichier, ai-je encore le temps de vous envoyer une nouvelle version d'ici ce soir ?

**Comment by PonteIneptique** [comment]
Bonjour.
Cette suppression n'a pas eu d'impact sur la note. Cependant, si vous
souhaitez tout de même le faire, n'hésitez pas. Dites le moi, c'est tout

**Comment by LucetteV** [comment]
@PonteIneptique : je reprends donc le travail de CelCpc.

**Comment by CelCpc** [comment]
Bonsoir, 

Suite à votre réponse, je vous informe que je viens à l'instant de renvoyer une version de mon texte où les balises <lb> réapparaissent. J'ai tenté de coller le plus d'hyphénisations possibles et de corriger le plus de fautes d'OCR que j'ai pu voir.

#168

**Comment by CelCpc** [comment]
@LucetteV Bonsoir, Je viens de voir ton message, si tu souhaites reprendre mon travail (car j'ai peut-être encore fait des oublis), n'hésite pas bien sûr.

**Comment by PonteIneptique** [comment]
Corrigé par le #168
