### ISSUE TITLE
Proposition de capitainisation du texte 

### ISSUE THREAD

**Issue by EmilieBlotiere** [Chartes-TNAH/patrologia_latina-dev#37]
Afin de faciliter la citation du texte, je propose de structurer le texte en suivant les guidelines CapiTains et en adaptant le RevisionDesc

**Comment by MarieCaro** [comment]
Il y a une faute de frappe pour le chapitre 5, et des petites modifications à faire aux URN, selon correction proposée sur le document.

**Comment by EmilieBlotiere** [comment]
les modifications ont été apportées au document.
Merci pour vos commentaires
