### ISSUE TITLE
stoa0040.stoa030a Correction OCR

### ISSUE THREAD

**Issue by EmilieBlotiere** [Chartes-TNAH/patrologia_latina-dev#78]
Bonjour,

dans la mesure du possible, j'ai corrigé les erreurs d'OCR. Toutefois n 'étant pas latiniste, il est possible qu'il persiste des corrections à faire. Cette correction a pour but de corriger les erreurs grossières afin de faire gagner du temps au scientifique qui reprendra ce texte.

**Comment by MarieCaro** [comment]
Très bonne initiative, merci
