### ISSUE TITLE
stoa0040.stoa030a. Modifications TEI header pour compatibilité CapiTainS

### ISSUE THREAD

**Issue by EmilieBlotiere** [Chartes-TNAH/patrologia_latina-dev#79]
J'ai modifié le header en complétant les balises REfsDecl et RefPattern en précisant l'indication des chapitres et sermons selon les CapiTainS Guidelines. Ainsi que les refState : chapitre et sermon.

**Comment by MarieCaro** [comment]
Les chemins XPath donnés dans le TEI Header ne permettent pas de sélectionner ce qu'ils devraient sélectionner.
Il y a aussi une coquille dans l'xml:lang du publisher, la langue devrait être "fra"

**Comment by EmilieBlotiere** [comment]
#80 j'ai vérifié les chemin xpath qui sont corrects me semble t il aux guidelines, après vérification, le xml: lang est bien fr;
Après vérification, j'ai corrigé le balisage des sermons en sous-chapitres.
