### ISSUE TITLE
Correction/ajouts in stoa0040/stoa015/stoa0040.stoa015.opp-lat1.xml

### ISSUE THREAD

**Issue by LucetteV** [Chartes-TNAH/patrologia_latina-dev#87]
Bonjour,

Cette issue pour vous avertir de la modification des "oe/OE" dans le corps du document xml. Ainsi que de l'ajout du xml:lang="la" ainsi que de l'ajout d'un @subtype="collection" dans la div de premier niveau.

Lucie

**Comment by Lwizzzzzz** [comment]
Les modifications ont bien été effectuées conformément à ce qui avait été annoncé par @LucetteV  (se référer à la pull request #76 ).
