### ISSUE TITLE
Résolution de l'erreur xml:lang

### ISSUE THREAD

**Issue by MaxDartois** [Chartes-TNAH/patrologia_latina-dev#88]
Capitains validator indique une erreur sur l'attribut xml:lang. 
Je vais intégrer cette balise sur la div de premier niveau.

**Comment by olivierjacquot** [comment]
L'ensemble des attributs xml:lang ont été vérifiés : xml:lang="la", "fr", et "grc". Ils sont conformes à http://www.stoa.org/epidoc/gl/latest/supp-language.html.
