### ISSUE TITLE
Modification des numérotations

### ISSUE THREAD

**Issue by MaxDartois** [Chartes-TNAH/patrologia_latina-dev#89]
Capitains Validator indique une erreur Duplicate passages, des numérotations de niveaux sont identiques. 
Pour résoudre ce problème, je vais modifier la numérotation des paragraphes en 1.1 etc.

**Comment by olivierjacquot** [comment]
Oui l'attribut n="x" des chapitres/paragraphes ne doit pas se répéter pour passer le test. Il faut contourner le problème en attribuant des numéros différents, par ex. une série de 1 à 9 et une série de 01 à 09, etc.

**Comment by MaxDartois** [comment]
Je viens de le modifier et de repasser cela sur Validator, plus d'erreurs de ce côté!
